import Link from "next/link";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb"

const TrermsCondition = () => {
    return (
       <div className="TC-page-body cart-page-body py-20">
            <div className="container">
                <Breadcrumb className="pb-8">
                    <BreadcrumbList>
                        <BreadcrumbItem>
                            <BreadcrumbLink asChild>
                                <Link href="/" className="font-pop textsm font-medium text-colorPrimary">Home</Link>
                            </BreadcrumbLink>
                        </BreadcrumbItem>
                        {/* <BreadcrumbItem>
                            <BreadcrumbLink asChild>
                                <Link href="/components">Components</Link>
                            </BreadcrumbLink>
                        </BreadcrumbItem> */}
                        <BreadcrumbSeparator />
                        <BreadcrumbItem>
                            <BreadcrumbPage className="font-pop textsm font-medium text-gray-500">Terms & Conditions</BreadcrumbPage>
                        </BreadcrumbItem>
                    </BreadcrumbList>
                </Breadcrumb>
                <div className="pt-5">
                    <h2 className="font-agd text-xl text-DarkPrimary p-0 m-0 mb-4 uppercase tracking-[1px]">Terms & Conditions</h2>
                    <p className="font-pop text-xs text-DarkPrimary p-0 m-0 mb-3">PLEASE READ THESE TERMS AND CONDITIONS OF USE AND ACCESS CAREFULLY. BY ACCESSING OR USING THE WEBSITE / MOBILE APPLICATION, YOU AGREE TO BE BOUND BY THE TERMS AND CONDITIONS DESCRIBED HEREIN AND ALL TERMS AND CONDITIONS INCORPORATED BY REFERENCE. IF YOU DO NOT AGREE TO ALL OF THESE TERMS AND CONDITIONS, DO NOT USE THE WEBSITE/ MOBILE APPLICATION.</p>

                    <p className="font-pop text-xs text-DarkPrimary p-0 m-0 mb-3">Use of the Sites by the user (“You”, “Your” “User and “Customers”) is subject to the terms and conditions contained herein.</p>
                    <p className="font-pop text-xs text-DarkPrimary p-0 m-0 mb-3">By visiting our Sites and/ or purchasing something from the Company, You engage in our services and agree to be bound by the following terms and conditions (“Terms of Use”/ “Terms”), including those additional terms and conditions and policies referenced herein and/or available by hyperlink These Terms of Use apply to your access to, and use of, all or part of this website www.burgerkingindia.in and/or mobile application (collectively, the “Sites”) of Restaurant Brands Asia Limited (herein after known as “the Company”, “RBAL”, “our”, “us” and “we”). These Terms of Use do not alter in any way the terms or conditions of any other agreement you may have with the Company for products, services or otherwise.</p>
                    <p className="font-pop text-xs text-DarkPrimary p-0 m-0 mb-3">These policies are published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, and are an ‘electronic record’ as contemplated under section 2(t) of the Information Technology Act, 2000 and the Rules thereunder. These Terms being an electronic record are generated by a computer system and do not require any physical or digital signatures.</p>
                    <p className="font-pop text-xs text-DarkPrimary p-0 m-0 mb-3">While we make reasonable efforts to provide accurate and timely information about the Company on the Sites, you should not assume that the information is always up to date or that the Sites contain all the relevant information available about the Company.</p>
                    <p className="font-pop text-xs text-DarkPrimary p-0 m-0 mb-3">The Company reserves the right to change, alter and/or modify these Terms of Use or any policy or guideline of the Sites including the Privacy Policy and Promotional T & C, at any time and in its sole discretion. Any changes or modifications will be effective immediately upon posting the revisions to the Sites, and you waive any right you may have to receive specific notice of such changes or modifications. Your continued use of the Sites will confirm your acceptance of such changes or modifications; therefore, you should frequently review these Terms of Use and applicable policies to understand the terms and conditions that apply to your use of our Sites. If you do not agree to the amended terms, you must stop using the Sites.</p>
                    <p className="font-pop text-xs text-DarkPrimary p-0 m-0 mb-3">The information contained in the Sites is for general purposes only. It should be noted that the contents, products and services available are provided on an “as is” and “as available” basis. We make no representations or warranties of any kind for any purpose, express or implied, about the completeness, accuracy, reliability or availability with respect to the website or the information, products, services or related graphics contained or depicted on the website. Any reliance you place on such information is, therefore, strictly at your own risk. RBAL does not warrant that any information obtained from or through the Sites is free from virus or other faults, defects or typographical error.</p>
                    <p className="font-pop text-xs text-DarkPrimary p-0 m-0 mb-3">RBAL shall not be accountable for any losses incurred as a result of any failure of service, mistake, omission, interruption, defect, delay in operation of transmission, computer virus, or line failure. There is no intent for the Sites to be used in a court of law.</p>

                    <h4 className="font-agd text-md text-DarkPrimary p-0 m-0 mb-2 mt-2 uppercase tracking-[1px]">Eligibility</h4>
                    <p className="font-pop text-xs text-DarkPrimary p-0 m-0 mb-3">The Company reserves the right to refuse access to use the services offered at the Application to new users or to terminate access granted to existing users at any time without according any reasons for doing so.</p>
                    <h4 className="font-agd text-md text-DarkPrimary p-0 m-0 mb-2 mt-2 uppercase tracking-[1px]">Acceptable uses and restrictions for the online services:</h4>
                    <p className="font-pop text-xs text-DarkPrimary p-0 m-0 mb-3">With respect to the online services (which includes content), you may not, and may not allow third parties, to:</p>
                    <ul className="pl-3">
                        <li className="mb-2 relative after:w-2 after:h-2 after:bg-black after:rounded-full after:absolute after:-left-3 after:top-[6px]">
                            <p className="font-pop text-xs text-DarkPrimary p-0 m-0 mb-3">Use the online services for any purpose that is unlawful or prohibited by these terms.</p>
                        </li>
                        <li className="mb-2 relative after:w-2 after:h-2 after:bg-black after:rounded-full after:absolute after:-left-3 after:top-[6px]">
                            <p className="font-pop text-xs text-DarkPrimary p-0 m-0 mb-3">Delete or change any copyright, trademark, or other proprietary notices.</p>
                        </li>
                        <li className="mb-2 relative after:w-2 after:h-2 after:bg-black after:rounded-full after:absolute after:-left-3 after:top-[6px]">
                            <p className="font-pop text-xs text-DarkPrimary p-0 m-0 mb-3">Attempt to obtain ownership or title to the online services, including the content.</p>
                        </li>
                    </ul>

                </div>
            </div> 
       </div>
    );
};
export default TrermsCondition;
